__version__ = "0.2.1"
__author__ = "Nico Schlömer"
__author_email__ = "nico.schloemer@gmail.com"
__copyright__ = f"Copyright (c) 2018-2020, {__author__} <{__author_email__}>"
__website__ = "https://github.com/nschloe/blacktex"
__license__ = "License :: OSI Approved :: MIT License"
__status__ = "Development Status :: 4 - Beta"
