#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
from __future__ import print_function

import argparse
import sys

import tidytex


def _main():
    args = _parse_options()
    data = args.infile.read()

    data = tidytex.clean(data)
    print(data, end="")
    return


def _parse_options():
    parser = argparse.ArgumentParser(description="Clean up LaTeX files.")

    parser.add_argument(
        "infile",
        nargs="?",
        type=argparse.FileType("r"),
        default=sys.stdin,
        help="input LaTeX file (default: stdin)",
    )

    parser.add_argument(
        "outfile",
        nargs="?",
        type=argparse.FileType("w"),
        default=sys.stdout,
        help="output LaTeX file (default: stdout)",
    )

    version_text = "tidytex {}, Python {}.{}.{}".format(
        tidytex.__version__,
        sys.version_info.major,
        sys.version_info.minor,
        sys.version_info.micro,
    )
    parser.add_argument("--version", "-v", action="version", version=version_text)

    return parser.parse_args()


if __name__ == "__main__":
    _main()
